have_fun: false

code_review:
  disable: false
  comment_severity_threshold: LOW
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: true
    code_review: true
    include_drafts: true

ignore_patterns:
  - '**/Library/**'
  - '**/Temp/**'
  - '**/Packages/**'
  - '**/ProjectSettings/**'
  - '**/*.meta'
  - '**/*.asset'
  - '**/node_modules/**'
